import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { navigationConfig } from '@/config'
import { Container, Header, ScrollTop } from '@/components'
import { MainNav } from '@/components/main-nav'
import { Footer } from '@/components/footer'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My blog',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} bg-primary text-gray-100`}>
        <Header>
          <MainNav items={navigationConfig} />
        </Header>
        <Container>
          <div className="pb-12 pt-24">{children}</div>
        </Container>
        <ScrollTop />
        <Footer items={navigationConfig} />
      </body>
    </html>
  )
}
