import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Container, Header } from '@/components'
import { headerConfig } from '@/config'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My blog',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-primary text-gray-100`}>
        <Header {...headerConfig} />
        <Container>
          <div className="py-24">{children}</div>
        </Container>
      </body>
    </html>
  )
}
