backend:
  name: github
  branch: main
  repo: kahzitacodes/next-blog
  base_url: https://next-blog-pi-lac.vercel.app
  auth_endpoint: api/auth

media_folder: public/assets/images
public_folder: /assets/images

publish_mode: editorial_workflow

slug:
  enconding: 'ascii'
  clean_accents: true

collections:
  - name: 'posts'
    label: 'Posts'
    extension: mdx
    format: 'frontmatter'
    folder: posts
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD hh:mm:ss', required: true }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Post image', name: 'image', widget: 'image', required: true }
      - { label: 'Tags', name: 'tags', widget: 'select', multiple: true, options: [
        'JavaScript',
        'TypeScript',
        'HTML',
        'NextJS',
        'ReactJS',
        'Misc',
        'Books',
      ] }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
